spring.application.name=orderService
server.port=9191
# Kafka Bootstrap Servers
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Producer Configurations
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.batch-size=16384
spring.kafka.producer.linger-ms=1
spring.kafka.producer.buffer-memory=33554432

# Additional Security Properties
spring.kafka.properties.security.protocol=PLAINTEXT

# Kafka Template Configurations
spring.kafka.template.default-topic=order-events
# Change the base path if needed (default is /actuator)
management.endpoints.web.base-path=/actuator

# Expose all web endpoints (or specify a comma-separated list like health,info,metrics)
management.endpoints.web.exposure.include=*

# Explicitly enable or disable specific endpoints if required
management.endpoint.health.enabled=true
management.endpoint.metrics.enabled=true